### PR TITLE
Fix ref: Neotomex.ParseError -> Neotomex.Grammar.ParseError

### PR DESCRIPTION
**Pull request by ddlsmurf**

### CODE REVIEW

**Comment by jtmoulia** [comment]
Awesome -- 🍻  to @ddlsmurf !

Do you need to me to cut a new minor version release with this bugfix?

**Comment by ddlsmurf** [comment]
Thanks =) This is a minor nuisance, just generates a warning (though I haven't tried invalid grammars yet), so I wouldn't mind one but only if it no inconvenience whatsoever, I can wait a couple of months without trouble.

**Comment by jtmoulia** [comment]
Hm I should embrace releasing often -- 0.1.6 is up on hex. Thanks again!

**Comment by ddlsmurf** [comment]
you're great thanks again !

**Pull request merged**
